#!/usr/bin/env bash

repo=$(basename "$PWD")

git init
echo "# My $repo Repository" > README.md
git add .
git commit -m "initial commit -setup with script"
git branch -M main
gh repo create "$repo"
git remote add origin git@github.com:yesiddgarzon/"$repo".git
git push -u origin main

echo ">>> You have created a github repo at https://github.com/$user/$repo"
