#!/usr/bin/env bash

user=$(yq e '."github.com".user' "$HOME"/.config/gh/hosts.yml)
repo=$(basename "$PWD")

git init
git add .
git commit -m "Initialize Repository"
git branch -M main
gh repo create "$repo"
git remote add origin git@github.com:"$user"/"$repo".git
git push -u origin main

echo ">>> You have created a github repo at https://github.com/$user/$repo"
