#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom -f &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
$HOME/.config/screenlayout/display.sh
lxsession &
xsetroot -cursor_name left_ptr &
setxkbmap es &
numlockx &
 
# disable screensaver                                                                                                                   
xset -dpms
xset s noblank
xset s off

# Monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# Bspwm config
bspc config automatic_scheme        alternate
bspc config border_width            1
bspc config window_gap              2
bspc config split_ratio             0.5
bspc config top_padding             0
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          false
bspc config click_to_focus          true
bspc config focus_by_distance       false
bspc config focus_follows_pointer   false 
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

# Applications 
bspc rule -a gimp desktop=III state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a virtualbox desktop='^2'
